CREATE DATABASE QUAN_LY_DIEM_SINH_VIEN;



USE QUAN_LY_DIEM_SINH_VIEN;
GO



CREATE TABLE Khoa
(
  MaKhoa INT PRIMARY KEY,
  TenKhoa NVARCHAR(100) NOT NULL
);

CREATE TABLE HeDaoTao
(
  MaHe INT PRIMARY KEY,
  TenHe NVARCHAR(100) NOT NULL
);

CREATE TABLE Lop
(
  MaLop INT PRIMARY KEY,
  TenLop NVARCHAR(100),
  MaKhoa INT,
  MaHe INT,
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
  FOREIGN KEY (MaHe) REFERENCES HeDaoTao(MaHe)
);
ALTER TABLE Lop
ADD SoLuongSinhVien INT DEFAULT 0;
UPDATE Lop
SET SoLuongSinhVien = (
    SELECT COUNT(*)
FROM SinhVien
WHERE SinhVien.MaLop = Lop.MaLop
);

CREATE TABLE SinhVien
(
  MaSV INT PRIMARY KEY,
  TenSV NVARCHAR(100) NOT NULL,
  NgaySinh DATE,
  GioiTinh NVARCHAR(10),
  MaLop INT,
  FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)
);

CREATE TABLE GiangVien
(
  MaGV INT PRIMARY KEY,
  TenGV NVARCHAR(100) NOT NULL,
  ChucVu NVARCHAR(50),
  MaKhoa INT,
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);

CREATE TABLE MonHoc
(
  MaMon INT PRIMARY KEY,
  TenMon NVARCHAR(100) NOT NULL,
  SoTinChi INT,
  MaKhoa INT,
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);

CREATE TABLE Diem
(
  MaSV INT,
  MaMon INT,
  DiemSo FLOAT,
  FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
  FOREIGN KEY (MaMon) REFERENCES MonHoc(MaMon)
);
